openapi: 3.0.0
info:
  title: M1_ContentProtocolsDiscovery
  version: 2.0.0
  description: |
    5GMS AF M1 Content Protocols Discovery API
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
tags:
  - name: M1_ContentDiscovery
    description: '5G Media Streaming: Provisioning (M1) APIs: Content Protocols Discovery'
externalDocs:
  description: 'TS 26.512 V17.2.0; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'
servers:
  - url: '{apiRoot}/3gpp-m1/v2'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 29.512 clause 6.1.
paths:
  /provisioning-sessions/{provisioningSessionId}/protocols:
    parameters:
      - name: provisioningSessionId
        in: path
        required: true
        schema: 
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26512_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of an existing Provisioning Session.'
    get:
      operationId: retrieveContentProtocols
      summary: 'Retrieve the set of Content Protocols supported by the specified Provisioning Session'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentProtocols'
components:
  schemas:
    ContentProtocolDescriptor:
      type: object
      description: "A descriptor describing a content protocol."
      required:
        - termIdentifier
      properties:
        termIdentifier:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        descriptionLocator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26512_CommonData.yaml#/components/schemas/Url'
    ContentProtocols:
      type: object
      description: "A representation of the Content Protocols resource."
      properties:
        downlinkIngestProtocols:
          type: array
          items:
            $ref: '#/components/schemas/ContentProtocolDescriptor'
          minItems: 1
        uplinkEgestProtocols:
          type: array
          items:
            $ref: '#/components/schemas/ContentProtocolDescriptor'
          minItems: 1
        geoFencingLocatorTypes:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1
