openapi: 3.0.0
info:
  title: Maf_SessionHandling_MetricsReporting
  version: 1.0.0
  description: |
    Media Delivery: Metrics Reporting API
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

tags:
  - name: Maf_SessionHandling_MetricsReporting
    description: 'Media Delivery: Metrics Reporting API'

externalDocs:
  description: 'TS 26.510 V18.0.0; Media Delivery; Interactions and APIs for media session handling'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.510/'

servers:
  - url: '{apiRoot}/3gpp-maf-session-handling/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 26.510 clause 7.1.3.

security:
  - {}
  - OAuth2: []

paths:
  /provisioning-sessions/{provisioningSessionId}/metrics-reporting/{metricsReportingConfigurationId}:
    parameters:
      - name: provisioningSessionId
        in: path
        required: true
        schema:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of an existing Provisioning Session.'
      - name: metricsReportingConfigurationId
        in: path
        required: true
        schema:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of a Metrics Configuration in the specified Provisioning Session.'
    post:
      operationId: submitMetricsReport
      summary: 'Submit a Metrics Report'
      security:
        - OAuth2:
          - metrics-report_submit
      requestBody:
        description: 'A Metrics Report'
        required: true
        content:
          application/3gpdash-qoe-report+xml:
            schema:
              type: string
              format: xml
          application/*:
            schema:
              type: string
      responses:
        '202': # Accepted: The request is well-formed but the message body has not yet been fully processed
          description: 'Metrics Report Accepted'
        '204': # No Content: The request is well-formed and the message body has been processed successfully
          description: 'Metrics Report Successful'
        '400': # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/400'
        '401': # Unauthorized
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/401'
        '403': # Forbidden: Metrics reporting is not provisioned
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/403'
        '411': # Length Required
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/411'
        '413': # Payload Too Large
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/413'
        '414': # URI Too Long
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/414'
        '415': # Unsupported Media Type
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/415'
        '500': # Internal Server Error
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/500'
        '503': # Service Unavailable
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes:
            metrics-report_submit: Submit a metrics report
        authorizationCode:
          authorizationUrl: '{authorizationUrl}'
          tokenUrl: '{tokenUrl}'
          scopes:
            metrics-report_submit: Submit a metrics report
