openapi: 3.0.0

info:
  title: 'MBS User Service Announcement'
  version: 1.4.1
  description: |
    MBS User Service Announcement Element units.
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 26.517 V17.7.0; 5G Multicast-Broadcast User Services; Protocols and Formats
  url: http://www.3gpp.org/ftp/Specs/archive/26_series/26.517/
paths:
  /user-service-descriptions:
    get:
      operationId: discoverUserServiceDescriptions
      summary: 'Discover User Service Descriptions'
      description: 'Discover User Service Descriptions that match the supplied query filter(s). At least one filter query parameter must be included in the request URL.'
      parameters:
        - in: query
          name: service-class
          schema:
            type: string
          required: true
          description: 'Filter for User Service Descriptions tagged with the supplied service class term identifier expressed as a fully-qualified URI string from a controlled vocabulary'
      responses:
        '200':
          # OK
          description: "Success"
          content:
            multipart/related:
              schema:
                type: string
        '204':
          # No Content (no matching User Service Descriptions)
          description: "No Matches Found"
        '500':
          # Internal Server Error
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/default'

  /user-service-descriptions/{externalServiceId}:
    get:
      operationId: retrieveUserServiceDescription
      summary: 'Retrieve User Service Description'
      description: 'Retrieve the User Service Description of a single service by supplying its external service identifier.'
      parameters:
        - name: externalServiceId
          in: path
          required: true
          schema:
            type: string
          description: 'The external service identifier of a User Service provisioned in the MBSF.'
      responses:
        '200':
          # OK
          description: "Success"
          content:
            multipart/related:
              schema:
                type: string
        '404':
          # Not Found
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          # Internal Server Error
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/default'

components:
  schemas:
    UserServiceDescriptions:
      description: 'A document announcing one or more MBS User Services.'
      type: object
      properties:
        version:
          type: integer
          minimum: 1
        userServiceDescriptions:
          type: array
          items:
            $ref: '#/components/schemas/UserServiceDescription'
          minItems: 1
      required:
        - userServiceDescriptions

    UserServiceDescription:
      description: 'A description of a single MBS User Service.'
      type: object
      properties:
        serviceIds:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1
        class:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        names:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              lang:
                type: string
                pattern: '^[a-zA-Z]{3}$'
                example: 'eng'
            required:
              - name
              - lang
          minItems: 1
        descriptions:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
              lang:
                type: string
                pattern: '^[a-zA-Z]{3}$'
                example: 'eng'
            required:
              - description
              - lang
          minItems: 1
        serviceLanguage:
          type: string
          pattern: '^[a-zA-Z]{3}$'
          example: 'eng'
        distributionSessionDescriptions:
          type: array
          items:
            $ref: '#/components/schemas/DistributionSessionDescription'
          minItems: 1
        serviceScheduleDescriptions:
          type: array
          items:
            $ref: '#/components/schemas/ServiceScheduleDescription'
          minItems: 1
      required:
        - serviceIds
        - class
        - distributionSessionDescriptions

    DistributionSessionDescription:
      type: object
      properties:
        distributionMethod:
          $ref: '#/components/schemas/DistributionMethod'
        conformanceProfiles:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1
        sessionDescriptionLocator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        applicationServiceDescriptions:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationServiceDescription'
          minItems: 1
        postSessionObjectRepairParameters:
          $ref: '#/components/schemas/ObjectRepairParameters'
        availabilityInfos:
          type: array
          items:
            $ref: '#/components/schemas/AvailabilityInformation'
          minItems: 1
        securityDescription:
          $ref: '#/components/schemas/SecurityDescription'
      required:
        - distributionMethod
        - sessionDescriptionLocator

    DistributionMethod:
      anyOf:
        - type: string
          enum:
            - OBJECT
            - PACKET
        - type: string
          description: >
            This string provides forward-compatibility with future
            extensions to the enumeration but is not used to encode
            content defined in the present version of this API.

    ApplicationServiceDescription:
      type: object
      properties: 
        entryPointLocator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        contentType:
          type: string
          pattern: '^[a-zA-Z]+\/[a-zA-Z]+$'
          example: 'application/dash+xml'
      required:
        - entryPointLocator
        - contentType

    AvailabilityInformation:
      type: object
      properties:
        mbsServiceAreas:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/MbsServiceArea'
          minItems: 1
        mbsFSAId:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/MbsFsaId'
        nrParameters:
          type: array
          items:
            $ref: '#/components/schemas/NrParameterSet'
          minItems: 1

    NrParameterSet:
      type: object
      properties:
        freqBandIndicator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uinteger'
        aRFCNValue:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uinteger'
      required:
        - freqBandIndicator
        - aRFCNValue

    ObjectRepairParameters:
      type: object
      properties:
        backOffParameters:
          $ref: '#/components/schemas/BackOffParameters'
        objectDistributionBaseLocator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        objectRepairBaseLocator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26512_CommonData.yaml#/components/schemas/AbsoluteUrl'
    BackOffParameters:
      type: object
      properties:
        offsetTime:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
        randomTimePeriod:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
      anyOf:
        - required: [offsetTime]
        - required: [randomTimePeriod]

    ServiceScheduleDescription:
      type: object
      properties:
         id:
           type: string
         version:
           type: integer
           minimum: 1
         start:
           $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DateTime'
         stop:
           $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DateTime'
      required:
        - id
        - version
        - start
        - stop

    SecurityDescription:
      type: object
      properties:
        mBSSFAddresses:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26512_CommonData.yaml#/components/schemas/AbsoluteUrl'
          minItems: 1
        mBSServiceKeyInfo:
          type: object
          properties:
            mBSId:
              type: string
            mBSDomainId:
              type: string
          required:
            - mBSId
            - mBSDomainId
        uICCKeyManagement:
          type: boolean
        2GGBAallowed:
          type: boolean
        backOffParameters:
          $ref: '#/components/schemas/BackOffParameters'
      required:
        - mBSSFAddresses
        - mBSSessionKeyInfo
