openapi: 3.0.0
info:
  title: Maf_SessionHandling_ServiceAccessInformation
  version: 1.0.1
  description: |
    Media Delivery: Service Access Information API
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

tags:
  - name: Maf_SessionHandling_ServiceAccessInformation
    description: 'Media Delivery: Service Access Information API'

externalDocs:
  description: 'TS 26.510 V18.1.0; Media Delivery; Interactions and APIs for media session handling'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.510/'

servers:
  - url: '{apiRoot}/3gpp-maf-session-handling/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 26.510 clause 7.1.3.

security:
  - {}
  - OAuth2: []

paths:
  /service-access-information/{externalServiceId}:
    parameters:
      - name: externalServiceId
        description: 'An external service identifier that uniquely identifies an existing Provisioning Session in this Media Delivery System.'
        in: path
        required: true
        schema:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
    get:
      operationId: retrieveServiceAccessInformation
      summary: 'Retrieve the Service Access Information resource'
      security:
        - OAuth2:
          - service-access-information_retrieve
      responses:
        '200': # OK
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccessInformationResource'
        '400': # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/400'
        '401': # Unauthorized
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/401'
        '404': # Not Found
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/404'
        '410': # Gone: Resource no longer exists
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/410'
        '413': # Payload Too Large: No request body allowed for this operation
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/413'
        '414': # URI too long
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/414'
        '500': # Internal Server Error
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/500'
        '503': # Service Unavailable
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/default' 

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes:
            service-access-information_retrieve: Retrieve Service Access Information resource
        authorizationCode:
          authorizationUrl: '{authorizationUrl}'
          tokenUrl: '{tokenUrl}'
          scopes:
            service-access-information-retreive: Retrieve Service Access Information resource

  schemas:
    AbsoluteMediaEntryPoint:
      description: "A typed entry point for downlink or uplink media streaming."
      type: object
      required:
        - locator
      oneOf:
        - required: [contentType]
        - required: [protocol]
      properties:
        locator:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/AbsoluteUrl'
        contentType:
          type: string
          description: "A MIME media content type."
        protocol:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
        profiles:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1

    ServerAddresses:
      description: "A set of application endpoint addresses."
      type: array
      items:
        $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/AbsoluteUrl'
      minItems: 1

    ServiceAccessInformationResource:
      description: "A representation of a Service Access Information resource."
      type: object
      required:
      - provisioningSessionId
      - provisioningSessionType
      - locationReporting
      properties:
        provisioningSessionId:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        provisioningSessionType:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ProvisioningSessionType'
        locationReporting:
          type: boolean
        notficationURL:
          readOnly: true
          allOf:
            - $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/AbsoluteUrl'
        streamingAccess:
          type: object
          properties:
            entryPoints:
              type: array
              items:
                $ref: '#/components/schemas/AbsoluteMediaEntryPoint'
            eMBMSServiceAnnouncementLocator:
              $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/AbsoluteUrl'
            mbsExternalServiceIdentifier:
              type: string
        rtcClientConfiguration:
          type: object
          properties:
            stunEndpoints:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/ClientServiceEndpointAccessParameters'
            turnEndpoints:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/ClientServiceEndpointAccessParameters'
            swapEndpoints:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/ClientServiceEndpointAccessParameters'
        clientConsumptionReportingConfiguration:
          type: object
          required:
            - serverAddresses
            - accessReporting
            - samplePercentage
          properties:
            reportingInterval:
              $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
            serverAddresses:
              $ref: '#/components/schemas/ServerAddresses'
            accessReporting:
              type: boolean
            samplePercentage:
              $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/Percentage'
        dynamicPolicyInvocationConfiguration:
          type: object
          required:
            - serverAddresses
            - policyTemplateBindings
            - sdfMethods
          properties: 
            serverAddresses:
              $ref: '#/components/schemas/ServerAddresses'
            policyTemplateBindings:
              type: array
              minItems: 1
              items: 
                type: object
                required:
                  - externalReference
                  - policyTemplateId
                properties: 
                  externalReference:
                    type: string
                  policyTemplateId:
                    $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
                  pduSetMarking:
                    type: boolean
                    default: false
                  bdtWindows:
                    type: array
                    minItems: 1
                    items:
                      $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/BdtWindow'
            sdfMethods:
              type: array
              items:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/SdfMethod'
              minItems: 0
        clientMetricsReportingConfigurations:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - metricsReportingConfigurationId
              - serverAddresses
              - scheme
              - samplePercentage
              - urlFilters
              - samplingPeriod
            properties:
              metricsReportingConfigurationId:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
              serverAddresses:
                $ref: '#/components/schemas/ServerAddresses'
              sliceScope:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Snssai'
                minItems: 1
              scheme:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
              dataNetworkName:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Dnn'
              reportingStartOffset:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
              reportingDuration:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
              reportingInterval:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
              samplePercentage:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/Percentage'
              urlFilters:
                type: array
                items:
                  type: string
                minItems: 0
              samplingPeriod:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/DurationSec'
              positiveCrossingThresholds:
                description: "A map (list of key-value pairs) for a metric and its positive crossing threshold values. The key of the map shall be a metric URI."
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Float'
                  minItems: 1
                minProperties: 1
              negativeCrossingThresholds:
                description: "A map (list of key-value pairs) for a metric and its negative crossing threshold values. The key of the map shall be a metric URI."
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Float'
                  minItems: 1
                minProperties: 1
              locationFilter:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29122_CommonData.yaml#/components/schemas/LocationArea5G'
                minItems: 1
              metrics:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uri'
                minItems: 1
        networkAssistanceConfiguration:
          type: object
          required: 
            - serverAddresses
          properties:
            serverAddresses:
              $ref: '#/components/schemas/ServerAddresses'
        clientEdgeResourcesConfiguration:
          type: object
          required:
            - easDiscoveryTemplate
          properties:
            eligibilityCriteria:
              $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/EdgeProcessingEligibilityCriteria'
            easDiscoveryTemplate:
              $ref: '#/components/schemas/EASDiscoveryTemplate'
            easRelocationRequirements:
              $ref: '#/components/schemas/ClientEASRelocationRequirements'

    ClientServiceEndpointAccessParameters:
      type: object
      description: "Details used by a Media Client to access a service endpoint."
      allOf:
        - $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/EndpointAddress'
        - type: object
          properties:
            credentials:
              type: object
              required:
                - username
                - passphrase
              properties:
                username:
                  type: string
                  minLength: 1
                passphrase:
                  type: string
                  minLength: 1

    ClientEASRelocationRequirements:
      description: 'Relocation requirements of an EAS.'
      type: object
      required:
        - tolerance
      properties:
        tolerance:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/EASRelocationTolerance'
        maxInterruptionDuration:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/UintegerRm'

    EASDiscoveryTemplate:
      description: 'A template for discovering an EAS instance .'
      type: object
      anyOf:
        - required: [easId]
        - required: [easType]
        - required: [easProviderIds]
        - required: [easFeatures]
      properties:
        easId:
          type: string
        easType:
          type: string
          minLength: 1
        easProviderIds:
          type: array
          items:
            type: string
            minLength: 1
          minItems: 1
        easFeatures:
          type: array
          items:
            type: string
            minLength: 1
          minItems: 1
