openapi: 3.0.0

info:
  title: M5_DynamicPolicies (deprecated)
  version: 3.0.2
  description: |
    5GMS AF M5 Dynamic Policy API
    © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

tags:
  - name: M5_DynamicPolicies
    description: '5G Media Streaming: Media Session Handling (M5) APIs: Dynamic Policies (deprecated)'

externalDocs:
  description: 'TS 26.512 V18.5.0; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'

paths: {}

components:
  schemas:
    DynamicPolicy:
      deprecated: true
      description: "A representation of a Dynamic Policy resource."
      type: object
      required:
        - dynamicPolicyId
        - policyTemplateId
        - serviceDataFlowDescriptions
        - provisioningSessionId
      properties:
        dynamicPolicyId:
          readOnly: true
          allOf:
            - $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        policyTemplateId:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        serviceDataFlowDescriptions:
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ApplicationFlowDescription'
        mediaType:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/MediaType'
        provisioningSessionId:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ResourceId'
        qosSpecification:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS26510_CommonData.yaml#/components/schemas/ClientQosSpecification'
        enforcementMethod:
          readOnly: true
          type: string
        enforcementBitRate:
          readOnly: true
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Uinteger'
