openapi: 3.0.1
info:
  title: MnS Registry NRM
  version: 18.6.0
  description: >-
    OAS 3.0.1 definition of the MnS Registry NRM fragment
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.623; Generic NRM, MnS Registry NRM
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.623/
paths: {}
components:
  schemas:
#-------- Definition of types-----------------------------------------------------

#-------- Definition of concrete IOCs --------------------------------------------          
    MnsRegistry-Single:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            MnsInfo:
              $ref: '#/components/schemas/MnsInfo-Multiple'

    MnsInfo-Single:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
             mnsLabel:
               type: string
             mnsType:
               type: string
               enum:
                 - ProvMnS
                 - FaultSupervisionMnS
                 - StreamingDataReportingMnS
                 - FileDataReportingMnS
             mnsVersion:
               type: string
             mnsAddress:
               description: Resource URI as defined in the relevant Technical Specification
               $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS28623_ComDefs.yaml#/components/schemas/Uri'
             mnsScope:
               description: >-
                 List of the managed object instances that can be accessed using the MnS.
                 If a complete SubNetwork can be accessed using the MnS, this attribute may 
                 contain the DN of the SubNetwork instead of the DNs of the individual managed 
                 entities within the SubNetwork.
               type: array
               items:
                 $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS28623_ComDefs.yaml#/components/schemas/Dn'

#-------- Definition of YAML arrays for name-contained IOCs ----------------------

    MnsInfo-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MnsInfo-Single'


#-------- Definitions in TS 28.623 for TS 28.532 ---------------------------------
    resources-mnSRegistryNrm:
      oneOf:
       - $ref: '#/components/schemas/MnsInfo-Single'
       - $ref: '#/components/schemas/MnsRegistry-Single'
