openapi: 3.0.0
info:
  title: 'Nspaf_SecuredPacket'
  version: '1.2.0'
  description: |
    Nspaf Secured Packet Service.  
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.544, SP-AF Services, version V18.2.0
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.544/
servers:
  - url: '{apiRoot}/nspaf-secured-packet/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
security:
  - {}
  - oAuth2ClientCredentials:
    - nspaf-secured-packet
paths:
  /{supi}/provide-secured-packet:
    post:
      summary: request generation of a secured packet
      operationId: ProvideSecuredPacket
      tags:
        - SecuredPacket Generation (Custom Operation)
      parameters:
        - name: supi
          in: path
          description: SUPI of the user
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/schemas/Supi'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UiccConfigurationParameter'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29503_Nudm_SDM.yaml#/components/schemas/SecuredPacket'
        '400':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/500'
        '502':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/502'
        '503':
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nspaf-secured-packet: Access to the nspaf-secured-packet API
  schemas:

# COMPLEX TYPES:

    UiccConfigurationParameter:
      description: Represents UICC Configuration Parameters.
      type: object
      oneOf:
        - required: [routingId ]
        - required: [steeringContainer ]
        - required: [extendedSteeringContainer ]
      properties:
        routingId:
          $ref: '#/components/schemas/RoutingId'
        steeringContainer:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29509_Nausf_SoRProtection.yaml#/components/schemas/SteeringInfo'
          minItems: 1
        extendedSteeringContainer:
          $ref: '#/components/schemas/ExtendedSteeringContainer'

    ExtendedSteeringContainer:
      description: Represents Extended Steering Containers.
      type: object
      properties:
        steeringContainer:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29509_Nausf_SoRProtection.yaml#/components/schemas/SteeringInfo'
          minItems: 1
        sorCmci:
          $ref: 'https://raw.githubusercontent.com/emanuelfreitas/3gpp-documentation/master/apis/TS29503_Nudm_SDM.yaml#/components/schemas/SorCmci'
        storeSorCmciInMe:
          type: boolean

# SIMPLE TYPES:

    RoutingId:
      description: Represents a routing indicator.
      type: string
      pattern: '^[0-9]{1,4}$'

# ENUMS:

